export { default as Hero } from "./Hero"
export { default as Contents } from "./Contents"
export { default as TextParallax } from "./TextParallax"
export { default as Canvas } from "./Canvas"
export { default as CanvasParallax } from "./CanvasParallax"
export { default as ScrollTriggerProxy } from "./ScrollTriggerProxy"